### ISSUE TITLE
Update project, with template improvement, add frontend and admin page.

### ISSUE THREAD

**Issue by gilcierweb** [nelsonfigueroa/personal-finance#76]
I cloned the project and updated the template with separate frontend and admin with different templates using tailwind. I added a translation and fixed some tables.
Are you interested in merging the changes into the current project?
There is still a lot to adjust.
![Captura de tela de 2024-10-22 21-48-51](https://github.com/user-attachments/assets/a49e6e1d-401a-45f4-84e6-1d72ad59579e)
![Captura de tela de 2024-10-22 21-48-27](https://github.com/user-attachments/assets/ae24969a-ca60-4c34-99db-b34c8b61940d)
![Captura de tela de 2024-10-22 21-48-19](https://github.com/user-attachments/assets/317ada1d-fef6-4085-a5f1-41dfd7cef7a8)
![Captura de tela de 2024-10-22 21-48-08](https://github.com/user-attachments/assets/6df2249f-b734-4efd-aa29-0ce1e0c518c2)
![Captura de tela de 2024-10-22 21-47-53](https://github.com/user-attachments/assets/0512b172-d192-4858-88da-08e337be4f1a)
![Captura de tela de 2024-10-22 21-47-35](https://github.com/user-attachments/assets/783291d9-4eb9-4a80-aa0d-06f4400d019b)
![Captura de tela de 2024-10-22 21-47-22](https://github.com/user-attachments/assets/fb0a1540-7d95-450d-9ef7-7f69df500bde)
![Captura de tela de 2024-10-22 21-47-06](https://github.com/user-attachments/assets/bf557c62-d4f7-4bab-b9f3-a94601e4245b)

**Comment by nelsonfigueroa** [comment]
Hey! I appreciate the effort. This is more of a personal project for me though and I don't want to merge this. Of course you are free to fork this repo and modify as you want.

**Comment by gilcierweb** [comment]
Okay, that's fine.
No problem.
Thanks for the feedback.
